export const ADD_INFO = "ADD_INFO";
export const GET_BOOKDESC_INFO = "GET_BOOKDESC_INFO";
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const GET_TASK_INFO = "GET_TASK_INFO";
export const GET_VIDEO = "GET_VIDEO";
export const GET_BOOK_TOTAL_PAGE = "GET_BOOK_TOTAL_PAGE";
export const STUDENTDATA = "STUDENTDATA";